// node calc.js — recalcule et affiche toutes les valeurs dérivées utilisées sur la page
const { C, D } = require('./data.js');
const f = (x) => x.toExponential(4);
const rows = [
  ['Section efficace Terre π·R² (m²)', f(D.earthCross)],
  ['Puissance solaire interceptée par la Terre (W)', f(D.P_EARTH)],
  ['Fraction de la luminosité reçue par la Terre', f(D.fractionEarth) + '  (1 sur ' + (D.oneIn/1e9).toFixed(2) + ' milliards)'],
  ['L = 4π·au²·S0 (W) [contrôle]', f(D.L_from_S0)],
  ['Masse convertie L/c² (kg/s)', f(D.massLoss) + '  (NSSDC: ' + f(C.MASS_CONV_NSSDC) + ')'],
  ['Hydrogène fusionné (kg/s)', f(D.hFused) + '  = ' + (D.hFused/1e9).toFixed(0) + ' millions de t/s'],
  ['Énergie Hiroshima (J)', f(D.HIROSHIMA_J)],
  ['Énergie Tsar Bomba (J)', f(D.TSAR_J)],
  ['Bombes Hiroshima / s (soleil)', f(D.hiroPerS)],
  ['Tsar Bomba / s (soleil)', f(D.tsarPerS)],
  ['Bombes Hiroshima / s reçues par la Terre', f(D.earthHiroPerS)],
  ['Temps pour que la Terre reçoive 1 an d\'énergie mondiale (s)', D.earthSecondsForWorldYear.toFixed(0) + ' s = ' + (D.earthSecondsForWorldYear/60).toFixed(1) + ' min'],
  ['Temps pour 1 an d\'énergie belge (s)', D.earthSecondsForBelgiumYear.toFixed(1)],
  ['Années d\'énergie mondiale émises par le soleil en 1 s', f(D.worldYearsPerSunSecond)],
  ['Puissance reçue par la Terre / puissance moyenne humanité', D.earthOverWorldPower.toFixed(0)],
  ['Rapport des diamètres', D.diamRatio.toFixed(2)],
  ['Rapport des volumes (R³)', f(D.volRatio) + '  (NSSDC: ' + C.VOL_RATIO_NSSDC + ')'],
  ['Temps lumière Soleil→Terre (s)', D.lightTime.toFixed(2) + ' = ' + Math.floor(D.lightTime/60) + ' min ' + (D.lightTime%60).toFixed(1) + ' s'],
  ['Charges de smartphone (15 Wh) par seconde de soleil', f(C.L_SUN / D.PHONE_J)],
  ['--- Comparaisons (EI 2025, année 2024) ---',''],
  ['Charbon : secondes de soleil sur Terre', D.secFor(D.COAL_J).toFixed(0)+' s = '+(D.secFor(D.COAL_J)/60).toFixed(1)+' min'],
  ['Nucléaire (chaleur) : secondes', D.secFor(D.NUCLEAR_J).toFixed(0)+' s = '+(D.secFor(D.NUCLEAR_J)/60).toFixed(2)+' min'],
  ['Nucléaire (électricité 2817,5 TWh) : secondes', D.secFor(D.NUCLEAR_ELEC_J).toFixed(1)+' s'],
  ['Rapport P_Terre / puissance moyenne charbon', (D.P_EARTH/(D.COAL_J/C.YEAR_S)).toFixed(0)],
  ['Rapport P_Terre / puissance moyenne nucléaire (chaleur)', (D.P_EARTH/(D.NUCLEAR_J/C.YEAR_S)).toFixed(0)],
  ['Rapport P_Terre / puissance moyenne nucléaire (élec.)', (D.P_EARTH/(D.NUCLEAR_ELEC_J/C.YEAR_S)).toFixed(0)],
  ['Puissance moyenne humanité (W)', f(D.humanPower)],
  ['--- Récolte solaire ---',''],
  ['Part atteignant la surface (185/340)', D.surfFrac.toFixed(3)],
  ['Puissance à la surface (W)', f(D.P_SURF)],
  ['Part des terres', D.landFrac.toFixed(3)],
  ['Puissance sur les terres (W)', f(D.P_LAND)],
  ['Soleil sur le Sahara entier (W)', f(D.P_SAHARA_SUN)],
  ['Sahara / terres émergées', (100*D.saharaShareOfLand).toFixed(2)+' %'],
  ['Électricité PV si 100 % Sahara couvert (W)', f(D.pvSahara100)+'  = '+(D.pvSahara100/D.humanPower).toFixed(1)+' × humanité'],
  ['% du Sahara pour égaler la consommation totale', D.saharaPctForHumanity.toFixed(2)+' %'],
  ['Potentiel technique GIEC SRREN / humanité', (C.SRREN_MIN_EJ/C.WORLD_EJ).toFixed(1)+' à '+(C.SRREN_MAX_EJ/C.WORLD_EJ).toFixed(0)+' ×'],
];
for (const [k, v] of rows) console.log(k.padEnd(66), v);
